create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  service text,
  city text,
  location text,
  date text,
  time text,
  message text,
  source_page text,
  enquiry_type text not null default 'general',
  email_status text not null default 'pending',
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists enquiries_submitted_at_idx on public.enquiries (submitted_at desc);
create index if not exists enquiries_email_idx on public.enquiries (email);

alter table public.enquiries enable row level security;

-- No public SELECT/INSERT policies are created.
-- The Vercel serverless endpoint uses the Supabase service-role key server-side.
