create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  service text,
  sport text,
  role text,
  city text,
  location text,
  preferred_area text,
  custom_area text,
  venue_address text,
  date text,
  time text,
  message text,
  source_page text,
  enquiry_type text not null default 'general',
  email_status text not null default 'pending',
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists enquiries_submitted_at_idx on public.enquiries (submitted_at desc);
create index if not exists enquiries_email_idx on public.enquiries (email);

alter table public.enquiries enable row level security;

-- No public SELECT/INSERT policies are created.
-- The Vercel serverless endpoint uses the Supabase service-role key server-side.


-- Safe migration for an existing enquiries table created before sport/role were added.
alter table public.enquiries add column if not exists sport text;
alter table public.enquiries add column if not exists role text;
alter table public.enquiries add column if not exists email_status text not null default 'pending';

-- Safe migration for preferred booking locality and venue address fields.
alter table public.enquiries add column if not exists preferred_area text;
alter table public.enquiries add column if not exists custom_area text;
alter table public.enquiries add column if not exists venue_address text;
